hack4impact-uiuc/mentee

backend/api/models/Education.py
backend/api/models/MentorProfile.py
backend/api/models/Video.py

Fixed Missing Init for Models and Added Constructor for Profile

---

README.md
backend/api/views/main.py

Takes a mentor ID as a parameter in the URL and returns the corresponding mentor as a GET request.
Fixes #4

GET mentor by ID

---

backend/api/models/Availability.py
backend/api/models/MentorProfile.py
backend/api/models/__init__.py

Availability will be represented as a list of objects with { startTime, endTime }, with querying explained here: https://stackoverflow.com/questions/42068483/mongodb-between-date-range-query-nested-property 
This should comply with Mongo's document schema, while allowing us to query efficiently.
Fixes #16

Adding availability model

---

frontend/src/components/css/Appointments.scss
frontend/src/components/css/Navigation.scss
frontend/src/components/pages/Appointments.js

Implemented the appointments tab in the Appointments page
Fixes #22

adding tabs to calendar page

---

frontend/src/components/NavigationSidebar.js
frontend/src/components/css/Appointments.scss
frontend/src/components/css/Navigation.scss
frontend/src/components/css/Profile.scss
frontend/src/components/pages/Profile.js

:rocket: Ready
* Make nav bars align closer to Faith's designs
* Make pages extend to full height of window
* Fix menu item spacing to get rid of this annoying gray bar on the right side of the sidebar (this took me so long to figure out jfc)
* Add shadow to sidebar
* Add profile CSS file
Before:
After:

Tweak nav styling

---

backend/api/__init__.py
backend/api/views/appointment.py

🚀 Done
Creates endpoint for PUT request for mentee appointments
Fixes #41 
DB before:
Postman:
DB after:

PUT Mentee Apointment

---

frontend/src/components/Navigation.js
frontend/src/components/css/Navigation.scss
frontend/src/components/css/Profile.scss
frontend/src/components/pages/Home.js
frontend/src/components/pages/Profile.js
frontend/src/components/pages/Videos.js

:rocket: Ready
* Create profile page in all its div'd glory
Resolves #33
* Replace placeholders with queried data

Create profile page template

---

frontend/src/components/App/App.js
frontend/src/components/MenteeNavHeader.js
frontend/src/components/MenteeNavigationHeader.js
frontend/src/components/MentorNavHeader.js
frontend/src/components/Navigation.js
frontend/src/components/NavigationSidebar.js
frontend/src/components/css/Navigation.scss
frontend/src/components/css/Profile.scss
frontend/src/components/pages/Gallery.js
frontend/src/components/pages/Home.js
frontend/src/components/pages/Profile.js

:rocket: Ready
* Build navbar for mentee side
* Differentiate between mentor/mentee pages navs
* Refactor some nav code and CSS
Resolves #53 
Temporary homepage
Click "mentor portal"
Click "find a mentor" (new gallery page)

🌐 Add general (mentee) navbar

---

backend/api/models/MentorProfile.py
backend/api/utils/request_utils.py
backend/api/views/main.py

:rocket: Ready
Adds location, phone number, and email to the mentor profile model and endpoints.
Fixes #67, #32 
What it looks like in database:

Add new fields to mentor profile

---

frontend/src/components/css/Gallery.scss
frontend/src/components/css/Home.scss
frontend/src/components/pages/Gallery.js
frontend/src/components/pages/Home.js
frontend/src/components/pages/Profile.js

:rocket: Ready
* Rename some styling for consistency and to prevent conflicts
* Add missing null checks in profile page
* Fix warnings

🧹 Clean up some frontend code

---

frontend/src/components/MentorCard.js
frontend/src/components/ProfileContent.js
frontend/src/components/css/Profile.scss

:rocket: Ready
PR #100 whooooo
* Add conditional rendering for optional fields in gallery (#93)
* Adjust education styling (#88)

Fix random styling bugs

---

frontend/src/components/MenteeButton.js
frontend/src/components/MenteeNavHeader.js
frontend/src/components/MentorCard.js
frontend/src/components/MentorProfileModal.js
frontend/src/components/ProfileContent.js
frontend/src/components/css/Gallery.scss
frontend/src/components/css/Home.scss
frontend/src/components/css/MenteeButton.scss
frontend/src/components/css/Navigation.scss
frontend/src/components/css/Profile.scss
frontend/src/components/pages/Home.js

:rocket: Ready
* Adds a wrapper component for all our buttons
* Fixes button styling bugs (e.g. blue border on hover from antd)
* Uses wrapper for pre-existing buttons (except for the appointments page because idk wtf is happening with that and it seems like it's standalone behavior anyways)
| Theme | Regular | Hover |
|---|---|---|
| Default | ![image](https://user-images.githubusercontent.com/36244017/99736614-4e288b00-2a8c-11eb-8f20-00bf62c6471d.png) | ![image](https://user-images.githubusercontent.com/36244017/99736602-479a1380-2a8c-11eb-9d4c-5b7837abbba0.png) |
| Light | ![image](https://user-images.githubusercontent.com/36244017/99736647-5aace380-2a8c-11eb-9ff8-ddd89edd284d.png) | ![image](https://user-images.githubusercontent.com/36244017/99736666-63051e80-2a8c-11eb-86f8-27067bdc6fe …

Add MenteeButton library component

---

backend/api/views/auth.py

Fixes #81 
Adds endpoints to resend verification email & reset password

Extra auth endpoints

---

frontend/src/components/css/AntDesign.scss
frontend/src/components/css/Gallery.scss
frontend/src/components/pages/Gallery.js
frontend/src/utils/consts.js

Fixes #96 
Filter by Specializations
Filter by Languages
Filter by Name
Filter by multiple queries

Implemented Filtering Feature

---

backend/api/models/AppointmentRequest.py
backend/api/utils/request_utils.py
backend/api/views/appointment.py

Fix FIelds on Appointment Request

---

frontend/src/components/css/Appointments.scss
frontend/src/components/pages/Appointments.js

Empty Appointments Lists

---

.github/workflows/deploy.yml

Testing stuff gonna auto merge because i dont know how to test github actions on a branch?

Github action deploy test

---

frontend/src/components/MentorCard.js
frontend/src/components/MentorNavHeader.js
frontend/src/components/NavigationSidebar.js
frontend/src/components/ProfileContent.js
frontend/src/components/css/Appointments.scss
frontend/src/components/css/Navigation.scss
frontend/src/components/css/_app.scss
frontend/src/components/pages/Appointments.js
frontend/src/components/pages/Home.js
frontend/src/components/pages/Profile.js
frontend/src/utils/misc.js

Fixes:
- mentor gallery links work now
- remove settings tab
- remove notif bell
- updated home text
- remove home link on mentor sidebar

Small bugfixes

---

frontend/src/components/MenteeAppointmentModal.js
frontend/src/components/css/MenteeModal.scss

Mobile Friendly Appointment Form

---

backend/api/models/MentorProfile.py
backend/api/views/appointment.py
frontend/src/components/css/Appointments.scss
frontend/src/components/pages/Appointments.js
frontend/src/components/pages/Register.js
frontend/src/components/pages/RegisterForm.js
frontend/src/components/pages/Verify.js
frontend/src/utils/auth.service.js
frontend/src/utils/consts.js
frontend/src/utils/dateFormatting.js

- Fixing 5:0 -> 5:00
- fixed registration flow issues- will redirect to the correct stage instead of skipping over verification when someone creates their acct
- removed save button from appointments calendar (we use the one in the modal now)
- added some * for required fields on the create profile form
- Cleaned up todos (mentor name in appts request, requiring user id for mentor profiles)

More bugfixes

---

backend/README.md
backend/api/utils/constants.py
backend/api/utils/request_utils.py
backend/api/views/appointment.py

Fixes #149 
* Updated send email function so it supports params for personalized email options
* Added dynamic template for Mentee Appointment Status

Mentee Appointment Notification

---

frontend/src/components/css/Home.scss
frontend/src/index.scss

On an Iphone 5 / Galaxy s5 it was unusable so I moved some css around. It also didn't fit well with Ipad pro

Homepage Responsive Fix

---

frontend/src/components/MenteeAppointmentModal.js
frontend/src/components/MentorCard.js
frontend/src/components/css/Gallery.scss

Fixes #196 
* added some type of indication that appointments are not available
* fixed overflow in text for gallery
* **However it needs to also be accounted for the profile too**
* skipped the last bug for now since I can't seem to replicate it...

CSS Bug Fixes

---

frontend/src/components/AdminSidebar.js
frontend/src/components/App/App.js
frontend/src/components/Navigation.js
frontend/src/components/css/Navigation.scss
frontend/src/components/css/_app.scss

Fixes #210 
- added admin sidebar

🧖‍♂️ Admin Sidebar

---

frontend/src/components/pages/AdminAccountData.js
frontend/src/utils/consts.js

* Quick link fix for a specific mentor profile
(it says port 5000, however, I changed it to 3000 since that is the default port for node)

Admin Account Data Bugfix 

---

backend/api/views/download.py
frontend/src/components/pages/AdminAccountData.js
frontend/src/components/pages/AdminAppointmentData.js
frontend/src/utils/api.js

Adds download all appointments btn to All Appointments page

👾 Add download all appointments btn

---

backend/README.md
frontend/src/components/AvailabilityCalendar.js
frontend/src/components/MentorCard.js
frontend/src/components/NavigationSidebar.js

🐠 Merge with master

---

backend/poetry.lock
backend/pyproject.toml
backend/requirements.txt
package.json
requirements.txt

Add additional backend dependencies

---

backend/poetry.lock
backend/pyproject.toml
backend/requirements.txt
package.json
requirements.txt

This reverts commit a01f732a0dba5d593a10bd6138317c06dc06e0da.
Fixes #number

Revert "Add dependencies (#261)"

---

backend/requirements.txt
package.json
requirements.txt

Remove requirements.txt hashes

---

backend/api/utils/firebase.py

Switch firebase env var

---

backend/api/models/MenteeProfile.py
backend/api/utils/require_auth.py
backend/api/views/admin.py
backend/api/views/appointment.py
backend/api/views/auth.py
backend/api/views/main.py
frontend/src/components/MentorNavHeader.js
frontend/src/components/MentorProfileModal.js
frontend/src/components/Navigation.js
frontend/src/components/UploadEmails.js
frontend/src/components/pages/AdminAccountData.js
frontend/src/components/pages/AdminAppointmentData.js
frontend/src/components/pages/AdminLogin.js
frontend/src/components/pages/ApplicationOrganizer.js
frontend/src/components/pages/Appointments.js
frontend/src/components/pages/Login.js
frontend/src/components/pages/Profile.js
frontend/src/components/pages/Register.js
frontend/src/components/pages/RegisterForm.js
frontend/src/components/pages/Videos.js
frontend/src/utils/api.js
frontend/src/utils/auth.service.js
frontend/src/utils/consts.js
frontend/src/utils/hooks/useAuth.js

Fixes:
* FIXED: users can have multiple kinds of accounts
* FIXED: on reload, sends back to login
* FIXED: on reload, navbar collaspes (need to wait for data before showing page)
* FIXED: MenteeProfile add firebase_uid
* FIXED: Add menteeId to login response

🥶 Update auth

---

backend/api/views/auth.py
frontend/src/components/pages/AdminLogin.js
frontend/src/components/pages/Register.js
frontend/src/components/pages/Verify.js
frontend/src/utils/hooks/useQuery.js

Allows admins to go through registration flow

🐪 Add Admin Register Ability

---

.github/workflows/prod-deploy.yml
frontend/src/components/css/Gallery.scss

Update prod deploy workflow

---

frontend/src/components/css/Modal.scss

👑Fix Mentor/Register Form 

---

backend/api/models/AppointmentRequest.py
backend/api/models/MenteeProfile.py
backend/api/models/MentorProfile.py
backend/api/utils/constants.py
backend/api/utils/request_utils.py
backend/api/views/appointment.py
frontend/src/components/AppointmentInfo.js
frontend/src/components/MenteeAppointmentModal.js
frontend/src/utils/consts.js
frontend/src/utils/dateFormatting.js

Fixes #301 
- Added status field
- added consts to both frontend/backend
- updated endpoints
- updated api/frontend handling

🏑 Add `Status` Field Appointments Schema

---

frontend/src/components/App/App.js
frontend/src/components/MenteeSidebar.js
frontend/src/components/pages/Favorites.js
frontend/src/components/pages/Messages.js
frontend/src/components/pages/SelectLogin.js

🔴Update Mentee Sidebar

---

backend/api/models/MentorApplication.py
backend/api/utils/require_auth.py
frontend/src/components/MentorAppInfo.js
frontend/src/components/MentorAppProgress.js
frontend/src/components/pages/ApplicationOrganizer.js
frontend/src/utils/consts.js

- Frontend was mishandling cases of undefined

🏈Fix Admin Mentor Applications

---

frontend/src/components/GuestNavHeader.js
frontend/src/components/pages/SelectLogin.js

🎶Mentee Portal Redirect Fix

---

backend/api/views/admin.py
frontend/src/utils/api.js

Fix delete mentor

---

backend/api/models/MenteeProfile.py
backend/api/models/MentorProfile.py
backend/api/utils/require_auth.py
backend/api/views/admin.py
frontend/src/utils/api.js

Fix mentor delete

---

backend/api/views/mentee.py
frontend/src/components/BookmarkSidebar.js
frontend/src/components/css/MenteeAppointments.scss
frontend/src/components/pages/Gallery.js
frontend/src/components/pages/MenteeAppointments.js
frontend/src/utils/api.js
frontend/src/utils/consts.js

Fixes #305 
- Added unfavorite functions
- created endpoint that provided necessary data for bookmark sidebar

📚 Bookmark Frontend Connection

---

frontend/src/components/css/Navigation.scss

✌ Mentee Messages Mobile Compatibility

---

frontend/package.json
frontend/src/components/MentorProfileModal.js
frontend/yarn.lock

✂Image Cropping Feature

---

c
frontend/src/components/css/Profile.scss

Temp Fix For Hidden Edit Contact

---

frontend/src/components/css/AdminAppointments.scss
frontend/src/components/css/Login.scss
frontend/src/components/css/SelectLogin.scss
frontend/src/index.scss

🎉Login Mobile Compatible

---

backend/api/views/download.py
frontend/src/components/pages/AdminAccountData.js
frontend/src/utils/api.js

Allows admins to download mentee data.

Add mentee accounts download

---

backend/api/utils/constants.py
backend/api/views/messages.py
frontend/src/components/MenteeAppointmentModal.js
frontend/src/components/MentorContactModal.js
frontend/src/components/ProfileContent.js
frontend/src/components/css/MenteeModal.scss
frontend/src/utils/api.js

Added a contact me in order to mitigate the lack of availability from Mentors

📞 Add contact me

---

README.md
docs/README.md

- Updated images that were not showing up and also titles
- Moved to a similar template to that of the [MERN Template](https://github.com/hack4impact-uiuc/mern-template)

🙎🏾 Update Doc/ReadMe

---

.github/workflows/emojify-pr.yml
README.md
backend/api/utils/constants.py
backend/api/views/auth.py
backend/api/views/messages.py
backend/requirements.txt
docs/README.md
frontend/src/components/GuestNavHeader.js
frontend/src/components/LoginVerificationModal.js
frontend/src/components/MenteeAppointmentModal.js
frontend/src/components/MenteeVerificationModal.js
frontend/src/components/MentorContactModal.js
frontend/src/components/ProfileContent.js
frontend/src/components/css/MenteeModal.scss
frontend/src/components/pages/Login.js
frontend/src/components/pages/MenteeRegisterForm.js
frontend/src/components/pages/Verify.js
frontend/src/utils/api.js
frontend/src/utils/auth.service.js
frontend/src/utils/consts.js
requirements.txt

- Added features that fix login issues especially with users logging in forever
- Added new contact me feature too

🔐 Dev To Master Payload

---

.gitignore
README.md
frontend/.gitignore

Added my info + updated .gitignore

😛 add Zayyan's name, image, and LinkedIn to README

---

README.md

👩🏻‍💻 Add Luciana to readme.md

---

README.md

:rocket: Ready
added new row to fit profiles nicely
Fixes #number

🌋 Fix README.md formatting

---

frontend/src/components/BookmarkSidebar.js
frontend/src/components/css/MenteeAppointments.scss
frontend/src/components/pages/MenteeAppointments.js
package.json

- when there are no favorited contacts, displays "no favorited contacts" instead of spinning icon 
Fixes #343

🥯 Favorite contacts bug fix

---

.gitignore

:rocket: Ready
Prevents .DS_Store from being committed in the root of the repository.

🤍 Add .DS_Store to root gitignore

---

backend/api/models/DirectMessage.py

🤦🏼‍♀️ Create Direct Message Backend Model

---

frontend/src/components/App/App.js
frontend/src/components/NavHeader.js
frontend/src/components/pages/Login.js
frontend/src/utils/hooks/useAuth.js

Reverts hack4impact-uiuc/mentee#391

Revert "👨🏽‍✈️ Nav Bar Visual Placeholder and Optimized Logout"

---

backend/api/__init__.py
backend/api/models/__init__.py
backend/api/views/notifications.py

:rocket: Ready
endpoint that gets the number of unread messages
Fixes #399

🧃 Add notifications endpoint

---

backend/requirements.txt
frontend/src/components/NavHeader.js
frontend/src/components/NotificationBell.js
frontend/src/components/css/Navigation.scss

👩🏻‍🌾 Add Notifications Bell

---

frontend/src/components/NavHeader.js
frontend/src/components/pages/Messages.js

:rocket: Ready
Adds button to go to user's messages

🧑🏼‍🚒 Add message button

---

frontend/src/components/NavHeader.js

:rocket: Ready
Look at title.
Fixes #number

🔧 fix empty message button

---

backend/api/views/messages.py
frontend/src/components/MenteeCard.js
frontend/src/components/MessageCard.js
frontend/src/components/MessagesChatArea.js
frontend/src/components/MessagesSidebar.js
frontend/src/components/pages/Messages.js

🧙🏼‍♂️ Messages cleanup

---

frontend/src/components/MentorCard.js

🗺️ Fixed mentor card url

---

backend/api/views/messages.py
frontend/src/components/MessageCard.js
frontend/src/components/MessagesChatArea.js
frontend/src/components/MessagesSidebar.js

🧑🏿‍🤝‍🧑🏻 Improve Messages Sidebar Load

---

backend/requirements.txt
frontend/src/components/MentorContactModal.js
frontend/src/components/ProfileContent.js
frontend/src/components/css/MenteeModal.scss
requirements.txt

🏌️‍♀️ Css contact me

---

backend/requirements.txt
frontend/src/components/MentorContactModal.js
frontend/src/components/MessagesChatArea.js
frontend/src/components/MessagesSidebar.js
frontend/src/components/ProfileContent.js
frontend/src/components/css/MenteeModal.scss
frontend/src/components/css/Messages.scss
frontend/src/components/pages/Messages.js
requirements.txt

Redid css to make messages look like designs [NOTE: known responsiveness issue on larger screens, need to fix later, pushing immediately for handoff]
Fixes #number

🍻 Revamped messaging css

---

frontend/src/components/ProfileContent.js

👨🏽‍🎨 Removed Book Appointment Button

---

frontend/src/components/MentorCard.js

Fixes #439 
- limits word limits in name, title, location, languages, and specializations
- add hover tool tip for fields that are cut off
^^^ lemme know your thoughts on the tooltip. I think it's intuitive/expected for an easy way to view the full length text if its truncated

🧑🏻‍🤝‍🧑🏾 Profile Card Overflow

---

frontend/src/components/pages/RegisterForm.js

Fixes #438 
just trust, it works

👰🏽‍♂️ Remove Duplicate Save on Create Profile

---

frontend/src/components/pages/RegisterForm.js

😙 force refresh

---

frontend/src/components/MessagesChatArea.js
frontend/src/components/MessagesSidebar.js
frontend/src/components/css/Messages.scss

🧜🏽 No Messages page

---

frontend/src/components/MessagesChatArea.js

message box should clear after a message is sent and scroll to the bottom of all messages. When the page first loads, it should show the most recent messages. 
Fixes #442

🧗🏽‍♂️ Clear message box + auto scroll to bottom

---

frontend/src/utils/consts.js

🧒 Added new skills and languages

---

frontend/src/components/css/Messages.scss
frontend/src/components/css/_app.scss

Fixes #432 
https://user-images.githubusercontent.com/29765024/147792436-82c26337-886d-4c7b-bf2d-9be20aea85b1.mov

💂🏻‍♀️ Anchored messaging input properly to footer

---

frontend/src/components/pages/Home.js

😎 Removed homepage tagline

---

frontend/src/components/css/Videos.scss
frontend/src/components/css/_app.scss
frontend/src/components/pages/Videos.js

- Fixed the weird shadow on the sidebar
- Changed background header color to match profile
- Fixed centering on videos table title
- Made header responsive across screen sizes (height static)
Fixes #434

Cleaned up videos page css

---

frontend/src/components/MentorContactModal.js
frontend/src/components/ProfileContent.js
frontend/src/components/css/Profile.scss
frontend/src/components/css/PublicProfile.scss

- Removed weird box shadows and simplified it to borders
- Corrected overflow for profile tags
- Added specializations for mentors
- Fixed a bunch of padding by making it static rather than dynamic
Note: There are other existing bugs that I didn't get to here, like how the height does not reach the whole screen for some reason, and a few other responsiveness issues. Will make an issue for them to be fixed in a later PR.
Fixes #433 
Mentor pages:
Mentee page (unaffected):

🙋 Cleaned up profile pages

---

frontend/src/components/css/Messages.scss

🛌🏻 Fixed messaging input anchor and text overflow

---

frontend/src/components/PublicMessageModal.js

🤰🏼 Fixed mentee send message

---

backend/api/views/appointment.py
frontend/src/components/MessagesSidebar.js
frontend/src/components/NavHeader.js
frontend/src/components/css/Messages.scss
frontend/src/utils/consts.js

- admin was not able to see mentor and mentee galleries
- admin portal link to mentor and mentee profiles was broken
- messages had whack CSS when user had a lot of people messaged

🧚🏼 Admin Portal + Messages Bugs

---

backend/api/models/MentorProfile.py
backend/api/utils/profile_parse.py
frontend/src/components/ProfileContent.js
frontend/src/components/pages/Appointments.js
frontend/src/components/pages/Profile.js

🎺 Add calender

---

backend/api/views/messages.py
frontend/src/components/MessagesChatArea.js
frontend/src/components/pages/Messages.js

✌🏽 Calender booking feature

---

backend/api/views/messages.py
frontend/src/components/MessagesChatArea.js
frontend/src/components/pages/Messages.js

🏌🏾‍♀️ Calender booking feature

---

frontend/src/components/AvailabilityCalendar.js
frontend/src/components/ProfileContent.js
frontend/src/components/pages/Appointments.js
frontend/src/utils/dateFormatting.js

🔧 Calendar mentor fixes

---

backend/api/__init__.py
backend/api/models/MenteeApplication.py
backend/api/models/PartnerProfile.py
backend/api/models/Training.py
backend/api/views/auth.py
backend/api/views/download.py
backend/api/views/main.py
backend/api/views/training.py
frontend/src/components/ProfileContent.js
frontend/src/components/css/Gallery.scss
frontend/src/components/pages/PartnerGallery.js

🛍️ Apply login partner changes

---

frontend/src/components/MentorCard.js
frontend/src/components/css/Gallery.scss
frontend/src/utils/consts.js

🧜🏽‍♀️ Apply login partner changes

---

backend/requirements.txt

⬆️ Mongo db upgrade

---

.github/workflows/dev-deploy.yml
.github/workflows/prod-deploy.yml

Addresses the following warnings from Git Actions:

👩🏼‍🎓 Update Git Actions

---

backend/api/utils/constants.py
backend/api/views/appointment.py
frontend/src/utils/consts.js

- Updated all code URL consts
- Updated Sendgrid URLs
- Connected heroku mentee-h4i project to app.menteeglobal.org
- Redirect old Vercel URL to new subdomain

🎅🏿 Update to app.menteeglobal.org

---

frontend/src/app/App.js
frontend/src/components/LoginVerificationModal.js
frontend/src/components/MentorCard.js
frontend/src/components/MessagesChatArea.js
frontend/src/components/NavHeader.js
frontend/src/components/Navigation.js
frontend/src/components/PartnerCard.js
frontend/src/components/ProfileContent.js
frontend/src/components/css/Navigation.scss
frontend/src/components/pages/AdminAccountData.js
frontend/src/components/pages/AdminAppointmentData.js
frontend/src/components/pages/AdminLogin.js
frontend/src/components/pages/ApplicationOrganizer.js
frontend/src/components/pages/Appointments.js
frontend/src/components/pages/Gallery.js
frontend/src/components/pages/Home.js
frontend/src/components/pages/Login.js
frontend/src/components/pages/MenteeAppointments.js
frontend/src/components/pages/MenteeGallery.js
frontend/src/components/pages/PartnerGallery.js
frontend/src/components/pages/Profile.js
frontend/src/components/pages/Videos.js
frontend/src/index.js
frontend/src/utils/auth.service.js
frontend/src/utils/fireauth.js
frontend/src/utils/hooks/useAuth.js

* 🧑🏿‍💻 Code cleanup (#638)
* formatting and print removals
* remove unused imports python
* formatting
* remove unused imports
* address firebase prod warning
* convert useAuth into provider
* formatting test
* formatting
* removed commented out code
* fixed broken profile content
Fixes #number

🌴 Firebase Authentication Rate Limit Issues (#648)

---

frontend/src/components/css/Navigation.scss

🧑🏼‍🤝‍🧑🏿 Navigation Height Fix

---

frontend/src/components/css/Navigation.scss

Restores overwritten code from navigation

🧘‍♂️ Fix Navigation height

---

frontend/src/components/AvailabilityCalendar.js
frontend/src/components/MenteeInterestModal.js
frontend/src/components/MenteeProfileModal.js
frontend/src/components/MentorProfileModal.js
frontend/src/components/PartnerProfileModal.js
frontend/src/components/ProfileContent.js
frontend/src/components/pages/Appointments.js
frontend/src/components/pages/PartnerGallery.js
frontend/src/components/pages/Profile.js
frontend/src/utils/auth.service.js

- Fixed broken API calls that were sending undefined profileIds from methods like getAdminId/getMentorId

🔧 Hotfix use profileId instead of getAccountId methods

---

backend/api/models/MentorProfile.py
backend/api/utils/constants.py
backend/api/views/training.py
frontend/src/app/App.js
frontend/src/components/pages/NewTrainingConfirm.js
frontend/src/utils/api.js
frontend/src/utils/consts.js

Email notification to users when admin creates new training material
Create confirm page for new material from email.

👳🏾‍♂️ email notification for new training

---

backend/api/models/MentorProfile.py
backend/api/utils/constants.py
backend/api/views/training.py
frontend/src/app/App.js
frontend/src/components/pages/NewTrainingConfirm.js
frontend/src/utils/api.js
frontend/src/utils/consts.js

remove admin@only for get train data

🦜 remove admin@only for get train data

---

frontend/src/components/NotificationBell.js

Fixes #462 
- Add on click event for bell that redirects you to messages page

😪 Notification Bell Update

---

backend/api/models/MentorProfile.py
backend/api/utils/constants.py
backend/api/views/training.py
frontend/src/app/App.js
frontend/src/components/NotificationBell.js
frontend/src/components/Trainings.js
frontend/src/components/css/TrainingList.scss
frontend/src/components/pages/NewTrainingConfirm.js
frontend/src/utils/api.js
frontend/src/utils/consts.js

email notification for new training
create page for check new training material

🙍🏾‍♂️ email notification for new training materail

---

frontend/src/utils/api.js

As title suggests just adding catch errors

🦇 Add Missing API Catch errors

---

frontend/src/components/NavHeader.js
frontend/src/utils/hooks/useAuth.js

Due to typing and cleaning up code `===` for role and `ACCOUNT_TYPE` enum differed by string/num
Changed useAuth to convert role into a number

🚣🏾 Fix Admin Notifications Navbar Type Checking

---

backend/api/models/MenteeProfile.py
backend/api/models/MentorProfile.py
backend/api/models/PartnerProfile.py
backend/api/utils/profile_parse.py
backend/api/views/main.py
frontend/src/components/AdminDataTable.js
frontend/src/components/ModalInput.js
frontend/src/components/NavHeader.js
frontend/src/components/css/AdminAccountData.scss
frontend/src/components/pages/AdminAccountData.js
frontend/src/components/pages/Gallery.js
frontend/src/components/pages/MenteeGallery.js

White label first release
1) Allow admin user to manually assign Mentor and Mentees to a Partner.  So a Partner will have users belonging to it.
2) Allow admin user to flag a partner as “restricted” partner or “full” partner.
3) As a Mentor/Mentee user profile, that logins to Mentee!, and is assigned to a Partner, if the Partner is “restricted”, then the Mentor/Mentee can interact (see, find, message) only with other Mentor/Mentees that belongs to the same partner - this will give privacy to the partner and the users belonging to it and segregate Mentee/Mentors to other users
4) As a Mentor/Mentee user profile, that logins to Mentee!, and is assigned to a Partner, if the Partner is “full”, then this user can interact (see, find, message) with any Mentee/Mentor for the platform, but not …

👯‍♀️ Assign users to partner

---

frontend/src/components/AvailabilityCalendar.js
frontend/src/components/pages/Appointments.js

Fixes #663 
* Fetch Appointments Bugs with missing Auth token
* Fix missing indicators for calendar having booked appointments
* Fixed Taking Appointments Checkbox not changing
https://user-images.githubusercontent.com/28935000/227080463-f8e55a1f-3c68-464f-8989-798aafaabbaa.mov

🤏🏾 Mentor Appointments Page Fix

---

frontend/src/components/AvailabilityCalendar.js
frontend/src/components/pages/Appointments.js

* fix fetch appointments issue
* fix missing booked appointments indicators
* fix taking appointments indicator
Fixes #number

🤏🏾 Mentor Appointments Page Fix (#675)

---

backend/api/views/training.py

Due to the current registration flow the new user doesn't even have a firebase uid so we need to open this endpoint up entirely.

🔧 Training Doc Bugfix

---

backend/api/views/masters.py
backend/api/views/notifications.py
backend/api/views/training.py

fix error of token when user not login

🐇 User token

---

backend/api/views/masters.py
backend/api/views/notifications.py
backend/api/views/training.py

fix error of token when user not login
As a Mentor / Mentee in the apply process, users are unable to open the PDF documents #688

👨🏼‍🚀 User token

---

backend/api/views/main.py
backend/api/views/masters.py
backend/api/views/notifications.py
backend/api/views/training.py

fix token error for build profile

🤱🏻 User token

---

backend/api/views/main.py
backend/api/views/masters.py
backend/api/views/notifications.py
backend/api/views/training.py

fix token error for build profile

🏓 User token

---

backend/api/views/main.py
backend/api/views/masters.py
backend/api/views/notifications.py
backend/api/views/training.py

fix token error for build profile

🥅 User token

---

backend/api/views/apply.py
backend/api/views/main.py
backend/api/views/masters.py
backend/api/views/notifications.py
backend/api/views/training.py
frontend/src/components/pages/Apply.js
frontend/src/utils/api.js

When users APPLY, they receive an email once APPROVED by Admin, I need that email to have a direct link to the user trainings, and after they complete the training receive another email, I need that email too with a direct link so that they build the profile.

Email with redirect to next step in application

---

backend/api/views/apply.py
backend/api/views/main.py
backend/api/views/masters.py
backend/api/views/notifications.py
backend/api/views/training.py
frontend/src/components/pages/Apply.js
frontend/src/utils/api.js

fix email template of app_approved and build_profile

🚶🏻 User token

---

.gitignore
README.md
backend/api/__init__.py
backend/api/views/apply.py
backend/api/views/main.py
backend/api/views/masters.py
backend/api/views/notifications.py
backend/api/views/training.py
backend/manage.py
frontend/src/components/pages/Apply.js
frontend/src/utils/api.js

🤷🏿‍♂️ User token

---

.gitignore
README.md
backend/api/__init__.py
backend/api/views/apply.py
backend/api/views/main.py
backend/api/views/masters.py
backend/api/views/notifications.py
backend/api/views/training.py
backend/manage.py
frontend/src/components/css/Apply.scss
frontend/src/components/css/Home.scss
frontend/src/components/css/Login.scss
frontend/src/components/css/SelectLogin.scss
frontend/src/components/pages/Apply.js
frontend/src/utils/api.js

🤶🏼 User token

---

.gitignore
README.md
backend/api/__init__.py
backend/api/views/apply.py
backend/api/views/main.py
backend/api/views/masters.py
backend/api/views/notifications.py
backend/api/views/training.py
backend/manage.py
frontend/src/components/css/Apply.scss
frontend/src/components/css/Home.scss
frontend/src/components/css/Login.scss
frontend/src/components/css/Navigation.scss
frontend/src/components/css/SelectLogin.scss
frontend/src/components/pages/Apply.js
frontend/src/components/pages/Home.js
frontend/src/utils/api.js

👱🏼‍♂️ User token

---

.gitignore
README.md
backend/api/__init__.py
backend/api/views/apply.py
backend/api/views/main.py
backend/api/views/masters.py
backend/api/views/notifications.py
backend/api/views/training.py
backend/manage.py
frontend/src/components/css/Apply.scss
frontend/src/components/css/Home.scss
frontend/src/components/css/Login.scss
frontend/src/components/css/Navigation.scss
frontend/src/components/css/SelectLogin.scss
frontend/src/components/pages/Apply.js
frontend/src/components/pages/Home.js
frontend/src/utils/api.js

👸🏽 User token

---

backend/api/__init__.py
backend/api/views/apply.py
backend/manage.py
frontend/src/components/pages/Login.js

Fixes #705 
- Add antd message component to display error

👩🏽‍💻 Login error display

---

frontend/public/locales/ar/translation.json
frontend/public/locales/fa-AF/translation.json
frontend/public/locales/pt-BR/translation.json
frontend/src/components/BookmarkSidebar.js
frontend/src/components/MenteeAppointmentModal.js
frontend/src/components/MenteeProfileModal.js
frontend/src/components/NavHeader.js
frontend/src/components/css/MenteeAppointments.scss
frontend/src/components/css/Modal.scss
frontend/src/utils/misc.js

Fixes #723 
- Reduce translations to fix some content containers
- Remove width defining issues

🕵🏿 CSS Translations Fix

---

frontend/src/components/ProfileContent.js

🌡️ Partner Profile Not Loading Fix

---

frontend/src/components/MentorApplicationView.js
frontend/src/components/pages/ApplicationOrganizer.js
frontend/src/components/pages/MenteeApplication.js
frontend/src/utils/consts.js

- Missing translations
- Admin page fixes

⛅ Dev to Master

---

frontend/src/components/css/Home.scss

🔧 fix css style

---

backend/api/utils/constants.py
backend/api/utils/google_translate.py
backend/api/utils/request_utils.py
backend/api/views/training.py
frontend/src/components/Trainings.js

🌎 Training Translation Bug Fix

---

frontend/src/components/MentorProfileModal.js
frontend/src/components/NavHeader.js
frontend/src/components/css/Login.scss
frontend/src/components/css/MenteeAppointments.scss
frontend/src/components/css/MenteeVideo.scss
frontend/src/components/css/Profile.scss
frontend/src/components/css/Register.scss
frontend/src/components/css/RegisterForm.scss
frontend/src/components/css/SelectLogin.scss
frontend/src/components/css/Videos.scss
frontend/src/components/pages/ForgotPassword.js
frontend/src/components/pages/Videos.js
frontend/src/features/optionsSlice.js
frontend/src/utils/api.js

http://mentee-dev.herokuapp.com/videos
http://mentee-dev.herokuapp.com/profile
http://mentee-dev.herokuapp.com/gallery/1/626bb8c6a4d6b218a3e62222 http://mentee-dev.herokuapp.com/mentee-appointments http://mentee-dev.herokuapp.com/forgot-password
fix mobile design of non admin user pages
http://mentee-dev.herokuapp.com/videos
http://mentee-dev.herokuapp.com/profile
http://mentee-dev.herokuapp.com/gallery/1/626bb8c6a4d6b218a3e62222
http://mentee-dev.herokuapp.com/mentee-appointments
http://mentee-dev.herokuapp.com/forgot-password

🧑‍🎨 Responsive design2

---

frontend/src/components/MentorProfileModal.js
frontend/src/components/MessageCard.js
frontend/src/components/NavHeader.js
frontend/src/components/css/Login.scss
frontend/src/components/css/MenteeAppointments.scss
frontend/src/components/css/MenteeVideo.scss
frontend/src/components/css/Profile.scss
frontend/src/components/css/Register.scss
frontend/src/components/css/RegisterForm.scss
frontend/src/components/css/SelectLogin.scss
frontend/src/components/css/Videos.scss
frontend/src/components/pages/ForgotPassword.js
frontend/src/components/pages/Videos.js
frontend/src/features/optionsSlice.js
frontend/src/utils/api.js

🎨 Responsive design2

---

backend/api/utils/profile_parse.py
frontend/src/components/css/Gallery.scss
frontend/src/components/pages/MentorProfileForm.js
frontend/src/components/pages/PublicProfile.js

- Fix breakpoints for profile card grids
- Fix missing introduction videos
- Conditionally render mentee videos if available

👫 Merge Dev to Master

---

backend/api/utils/constants.py
backend/api/utils/profile_parse.py
backend/api/views/apply.py
backend/api/views/main.py
frontend/src/components/AdminDataTable.js
frontend/src/components/AdminDropdowns.js
frontend/src/components/PartnerProfileForm.js
frontend/src/components/pages/AdminAccountData.js
frontend/src/components/pages/MenteeProfileForm.js
frontend/src/components/pages/MentorProfileForm.js

🕹️ Manage guests

---

frontend/src/components/AddAppointmentModal.js
frontend/src/components/AvailabilityCalendar.js
frontend/src/components/css/Appointments.scss
frontend/src/components/css/AvailabilityCalendar.scss
frontend/src/components/pages/Appointments.js

- Clean up appointments page code
- Made a new modal file for add appointments
- Create drawer for mobile design

🧗🏽‍♂️ Mentor Appointments Fixes

---

frontend/public/locales/ar/translation.json
frontend/public/locales/en-US/translation.json
frontend/public/locales/es-US/translation.json
frontend/public/locales/fa-AF/translation.json
frontend/public/locales/pa-AR/translation.json
frontend/public/locales/pt-BR/translation.json
frontend/src/components/PartnerProfileForm.js
frontend/src/components/pages/BuildProfile.js

🐛 Fix partner form bug

---

tests/cypress/e2e/pages/GuestLogin.js
tests/cypress/e2e/test/GuestLoggedInPage.cy.js
tests/cypress/e2e/test/MentorVideopageTest.cy.js
tests/cypress/e2e/test/ProfileTest.cy.js

🔧 Uncomment The fixes testcases

---

backend/tests/test_explore.py
tests/cypress.config.js
tests/cypress/e2e/pages/AdminAccountDataPage.js

👩🏽‍🦱 Frontend test cases

---

backend/tests/test_explore.py

🤵 Remove the data test case

---

requirements.txt

👨🏽‍🍼 Update requirements.txt

---

frontend/src/components/pages/MenteeApplication.js

fix select mode of mentee application form

🔧 fix select mode of mentee application form

---

frontend/src/components/EventCard.js
frontend/src/components/pages/EventDetail.js
frontend/src/utils/api.js

👩‍🎓 from new branch

---

docs/README.md

heroku-24 test

---

docs/README.md

updated heroku stack to heroku-22 from heroku-20

test merge heroku update

---

backend/api/models/Admin.py
backend/api/models/Guest.py
backend/api/models/Hub.py
backend/api/models/MenteeProfile.py
backend/api/models/MentorProfile.py
backend/api/models/PartnerProfile.py
backend/api/models/Support.py
backend/api/models/Users.py
backend/api/utils/profile_parse.py
backend/api/views/main.py
frontend/public/locales/ar/translation.json
frontend/public/locales/en-US/translation.json
frontend/public/locales/es-US/translation.json
frontend/public/locales/fa-AF/translation.json
frontend/public/locales/pa-AR/translation.json
frontend/public/locales/pt-BR/translation.json
frontend/src/components/CreateMeetingLink.js

🥾 Fix meeting

---

backend/api/views/messages.py
frontend/public/locales/en-US/translation.json
frontend/src/components/MessageCard.js
frontend/src/components/MessagesChatArea.js
frontend/src/components/MessagesSidebar.js
frontend/src/components/SearchMessageCard.js
frontend/src/components/css/Messages.scss
frontend/src/components/pages/Messages.js
frontend/src/utils/api.js

🧍🏽 Search feature and UI refactor work in messages page

---

frontend/public/locales/ar/translation.json
frontend/public/locales/en-US/translation.json
frontend/public/locales/es-US/translation.json
frontend/public/locales/fa-AF/translation.json
frontend/public/locales/pa-AR/translation.json
frontend/public/locales/pt-BR/translation.json
frontend/src/components/MessagesChatArea.js
frontend/src/components/MessagesSidebar.js
frontend/src/components/pages/Messages.js

🔧 Loading implement and fix mobile bug

---

backend/api/views/messages.py
frontend/public/locales/ar/translation.json
frontend/public/locales/en-US/translation.json
frontend/public/locales/es-US/translation.json
frontend/public/locales/fa-AF/translation.json
frontend/public/locales/pa-AR/translation.json
frontend/public/locales/pt-BR/translation.json
frontend/src/components/MessageCard.js
frontend/src/components/MessagesChatArea.js
frontend/src/components/MessagesSidebar.js
frontend/src/components/SearchMessageCard.js
frontend/src/components/css/Messages.scss
frontend/src/components/pages/Messages.js
frontend/src/utils/api.js

👵🏼 Message Feature

---

frontend/src/components/css/Messages.scss

🤭 Fix Layout Issue

---

frontend/src/components/css/Messages.scss

🤾🏿‍♀️ Fix Layout Issue

---

frontend/public/locales/en-US/translation.json
frontend/src/app/App.js
frontend/src/components/LoginForm.js
frontend/src/components/MessageCard.js
frontend/src/components/NavigationHeader.js
frontend/src/components/ProfileContent.js
frontend/src/components/TrainingList.js
frontend/src/components/css/AdminAccountData.scss
frontend/src/components/css/Appointments.scss
frontend/src/components/css/Home.scss
frontend/src/components/css/Messages.scss
frontend/src/components/css/Profile.scss
frontend/src/components/css/Training.scss
frontend/src/components/pages/AnnouncementDetail.js
frontend/src/components/pages/Announcements.js
frontend/src/components/pages/Appointments.js
frontend/src/components/pages/Events.js
frontend/src/components/pages/Profile.js
frontend/src/components/pages/TrainingData.js

🧑🏻‍🦲 Fix UI Issues

---

frontend/src/components/LoginForm.js

👩🏿‍⚖️ Fix Login Issue

---

backend/api/views/training.py

🔧 fix import issue

---

frontend/src/app/App.js
frontend/src/components/pages/AdminTraining.js
frontend/src/components/pages/HomeLayout.js

🔧 Zindex fix

---

backend/api/models/Training.py
backend/api/views/training.py
frontend/package.json
frontend/public/locales/en-US/translation.json
frontend/src/app/App.js
frontend/src/components/LoginForm.js
frontend/src/components/MessageCard.js
frontend/src/components/NavigationHeader.js
frontend/src/components/ProfileContent.js
frontend/src/components/TrainingList.js
frontend/src/components/css/AdminAccountData.scss
frontend/src/components/css/Appointments.scss
frontend/src/components/css/Home.scss
frontend/src/components/css/Messages.scss
frontend/src/components/css/Profile.scss
frontend/src/components/css/Training.scss
frontend/src/components/pages/AdminTraining.js
frontend/src/components/pages/AnnouncementDetail.js
frontend/src/components/pages/Announcements.js
frontend/src/components/pages/Appointments.js
frontend/src/components/pages/Events.js
frontend/src/components/pages/HomeLayout.js
frontend/src/components/pages/Profile.js
frontend/src/components/pages/TrainingData.js
frontend/src/utils/api.js

🙋🏽 dnd feature

---

backend/.gitignore
backend/api/models/GroupMessage.py
backend/api/views/messages.py
frontend/public/locales/ar/translation.json
frontend/public/locales/en-US/translation.json
frontend/public/locales/es-US/translation.json
frontend/public/locales/fa-AF/translation.json
frontend/public/locales/pa-AR/translation.json
frontend/public/locales/pt-BR/translation.json
frontend/src/components/GroupMessageChatArea.js
frontend/src/components/HubFooter.js
frontend/src/components/css/Messages.scss
package.json

Added group chat "title" feature

🤽‍♂️ Add title to group chat messages with clean setup

---

.github/workflows/dev-deploy.yml
backend/.gitignore
backend/api/models/GroupMessage.py
backend/api/views/messages.py
frontend/public/locales/ar/translation.json
frontend/public/locales/en-US/translation.json
frontend/public/locales/es-US/translation.json
frontend/public/locales/fa-AF/translation.json
frontend/public/locales/pa-AR/translation.json
frontend/public/locales/pt-BR/translation.json
frontend/src/components/GroupMessageChatArea.js
frontend/src/components/HubFooter.js
frontend/src/components/css/Messages.scss
package.json

updated dev deploy after issue

🧏‍♀️ Feature/group messages title dev

---

frontend/src/components/PartnerProfileForm.js
frontend/src/components/ProfileContent.js
frontend/src/components/pages/PartnerGallery.js

👃🏾 Revert " req#1 (#1190)"

---

frontend/src/components/GroupMessageChatArea.js

Updated UI group messages chat

🧏‍♂️ Modified Group Chat layout

---

backend/api/views/notifications.py
backend/scripts/emails.py

💁‍♂️ Fix weekly emails JWT issue

---

frontend/src/components/GroupMessageChatArea.js

for fixing merge bug
Fixes #number

📭 Update GroupMessageChatArea.js

---

backend/api/utils/flask_imgur.py
backend/api/views/appointment.py
backend/api/views/download.py
backend/api/views/main.py
backend/api/views/notifications.py
backend/scripts/emails.py

Always send notifications regardless of user preferences

👩‍🌾 Feature/notifications without profile check

---

backend/api/views/notifications.py

This change modifies the alert message used from sendgrid for common messages

🥽 modified sendgrid template for common messages

---

backend/api/views/notifications.py
frontend/src/components/GroupMessageChatArea.js

👩🏿‍🤝‍👩🏽 Changenotificationgroup

---

backend/scripts/emails.py

🔧 fixes request get weeklyemails api

---

frontend/src/components/GroupMessageChatArea.js
frontend/src/components/css/Messages.scss

:rocket: Ready
Adjust chat container max‑height on mobile to improve footer spacing
Old Version
New Version

👈🏽 Improve responsive layout of chat footer

---

frontend/src/components/HubFooter.js
frontend/src/components/css/Messages.scss
frontend/src/components/css/Navigation.scss

👩🏽‍🦯 Fix/messages btn

---

backend/api/views/download.py

👳🏼‍♀️ Added affiliation
